// Code generated by /internal/packages/generator DO NOT EDIT
package encryption

import "github.com/readykit/gd"

type HashingContextHashType int64

const (
	HashingContextHashMd5 HashingContextHashType = 0
	HashingContextHashSha1 HashingContextHashType = 1
	HashingContextHashSha256 HashingContextHashType = 2
)

type Crypto = gd.Crypto

type CryptoKey = gd.CryptoKey

type HashingContext = gd.HashingContext
