// Code generated by the generate package DO NOT EDIT

// Package AudioStreamGeneratorPlayback provides methods for working with AudioStreamGeneratorPlayback object instances.
package AudioStreamGeneratorPlayback

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/AudioStreamPlayback"
import "graphics.gd/classdb/AudioStreamPlaybackResampled"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector2"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create an extension of this class.
T should be the type that is embedding this [Extension]
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
This class is meant to be used with [AudioStreamGenerator] to play back the generated audio in real-time.
*/
type Instance [1]gdclass.AudioStreamGeneratorPlayback

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	push_frame           gdextension.MethodForClass `hash:"3975407249"`
	can_push_buffer      gdextension.MethodForClass `hash:"1116898809"`
	push_buffer          gdextension.MethodForClass `hash:"1361156557"`
	get_frames_available gdextension.MethodForClass `hash:"3905245786"`
	get_skips            gdextension.MethodForClass `hash:"3905245786"`
	clear_buffer         gdextension.MethodForClass `hash:"3218959716"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("AudioStreamGeneratorPlayback")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		gdextension.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsAudioStreamGeneratorPlayback() Instance
}

/*
Pushes a single audio data frame to the buffer. This is usually less efficient than [method push_buffer] in C# and compiled languages via GDExtension, but [method push_frame] may be [i]more[/i] efficient in GDScript.
*/
func (self Instance) PushFrame(frame_ Vector2.XY) bool { //gd:AudioStreamGeneratorPlayback.push_frame
	return bool(Advanced(self).PushFrame(Vector2.XY(frame_)))
}

/*
Returns [code]true[/code] if a buffer of the size [param amount] can be pushed to the audio sample data buffer without overflowing it, [code]false[/code] otherwise.
*/
func (self Instance) CanPushBuffer(amount int) bool { //gd:AudioStreamGeneratorPlayback.can_push_buffer
	return bool(Advanced(self).CanPushBuffer(int64(amount)))
}

/*
Pushes several audio data frames to the buffer. This is usually more efficient than [method push_frame] in C# and compiled languages via GDExtension, but [method push_buffer] may be [i]less[/i] efficient in GDScript.
*/
func (self Instance) PushBuffer(frames []Vector2.XY) bool { //gd:AudioStreamGeneratorPlayback.push_buffer
	return bool(Advanced(self).PushBuffer(Packed.New(frames...)))
}

/*
Returns the number of frames that can be pushed to the audio sample data buffer without overflowing it. If the result is [code]0[/code], the buffer is full.
*/
func (self Instance) GetFramesAvailable() int { //gd:AudioStreamGeneratorPlayback.get_frames_available
	return int(int(Advanced(self).GetFramesAvailable()))
}

/*
Returns the number of times the playback skipped due to a buffer underrun in the audio sample data. This value is reset at the start of the playback.
*/
func (self Instance) GetSkips() int { //gd:AudioStreamGeneratorPlayback.get_skips
	return int(int(Advanced(self).GetSkips()))
}

/*
Clears the audio sample data buffer.
*/
func (self Instance) ClearBuffer() { //gd:AudioStreamGeneratorPlayback.clear_buffer
	Advanced(self).ClearBuffer()
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.AudioStreamGeneratorPlayback

func (self class) AsObject() [1]gd.Object { return self[0].AsObject() }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.AudioStreamGeneratorPlayback](obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.AudioStreamGeneratorPlayback](obj[0])
		return true
	}
	return false
}
func (self Instance) AsObject() [1]gd.Object      { return self[0].AsObject() }
func (self *Extension[T]) AsObject() [1]gd.Object { return self.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.AudioStreamGeneratorPlayback{pointers.Add[gdclass.AudioStreamGeneratorPlayback]([3]uint64{})})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(pointers.AsA[gd.Object](placeholder[0]), raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.AudioStreamGeneratorPlayback{pointers.New[gdclass.AudioStreamGeneratorPlayback]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))})})
	casted.AsRefCounted()[0].InitRef()
	casted.AsObject()[0].Notification(0, false)
	return casted
}

/*
Pushes a single audio data frame to the buffer. This is usually less efficient than [method push_buffer] in C# and compiled languages via GDExtension, but [method push_frame] may be [i]more[/i] efficient in GDScript.
*/
//go:nosplit
func (self class) PushFrame(frame_ Vector2.XY) bool { //gd:AudioStreamGeneratorPlayback.push_frame
	var r_ret = gdextension.Call[bool](gd.ObjectChecked(self.AsObject()), methods.push_frame, gdextension.SizeBool|(gdextension.SizeVector2<<4), &struct{ frame_ Vector2.XY }{frame_})
	var ret = r_ret
	return ret
}

/*
Returns [code]true[/code] if a buffer of the size [param amount] can be pushed to the audio sample data buffer without overflowing it, [code]false[/code] otherwise.
*/
//go:nosplit
func (self class) CanPushBuffer(amount int64) bool { //gd:AudioStreamGeneratorPlayback.can_push_buffer
	var r_ret = gdextension.Call[bool](gd.ObjectChecked(self.AsObject()), methods.can_push_buffer, gdextension.SizeBool|(gdextension.SizeInt<<4), &struct{ amount int64 }{amount})
	var ret = r_ret
	return ret
}

/*
Pushes several audio data frames to the buffer. This is usually more efficient than [method push_frame] in C# and compiled languages via GDExtension, but [method push_buffer] may be [i]less[/i] efficient in GDScript.
*/
//go:nosplit
func (self class) PushBuffer(frames Packed.Array[Vector2.XY]) bool { //gd:AudioStreamGeneratorPlayback.push_buffer
	var r_ret = gdextension.Call[bool](gd.ObjectChecked(self.AsObject()), methods.push_buffer, gdextension.SizeBool|(gdextension.SizePackedArray<<4), &struct {
		frames gdextension.PackedArray[Vector2.XY]
	}{pointers.Get(gd.InternalPacked[gd.PackedVector2Array, Vector2.XY](frames))})
	var ret = r_ret
	return ret
}

/*
Returns the number of frames that can be pushed to the audio sample data buffer without overflowing it. If the result is [code]0[/code], the buffer is full.
*/
//go:nosplit
func (self class) GetFramesAvailable() int64 { //gd:AudioStreamGeneratorPlayback.get_frames_available
	var r_ret = gdextension.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_frames_available, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Returns the number of times the playback skipped due to a buffer underrun in the audio sample data. This value is reset at the start of the playback.
*/
//go:nosplit
func (self class) GetSkips() int64 { //gd:AudioStreamGeneratorPlayback.get_skips
	var r_ret = gdextension.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_skips, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Clears the audio sample data buffer.
*/
//go:nosplit
func (self class) ClearBuffer() { //gd:AudioStreamGeneratorPlayback.clear_buffer
	gdextension.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.clear_buffer, 0, &struct{}{})
}
func (self class) AsAudioStreamGeneratorPlayback() Advanced {
	return Advanced{pointers.AsA[gdclass.AudioStreamGeneratorPlayback](self[0])}
}
func (self Instance) AsAudioStreamGeneratorPlayback() Instance {
	return Instance{pointers.AsA[gdclass.AudioStreamGeneratorPlayback](self[0])}
}
func (self *Extension[T]) AsAudioStreamGeneratorPlayback() Instance {
	return self.Super().AsAudioStreamGeneratorPlayback()
}
func (self class) AsAudioStreamPlaybackResampled() AudioStreamPlaybackResampled.Advanced {
	return AudioStreamPlaybackResampled.Advanced{pointers.AsA[gdclass.AudioStreamPlaybackResampled](self[0])}
}
func (self *Extension[T]) AsAudioStreamPlaybackResampled() AudioStreamPlaybackResampled.Instance {
	return self.Super().AsAudioStreamPlaybackResampled()
}
func (self Instance) AsAudioStreamPlaybackResampled() AudioStreamPlaybackResampled.Instance {
	return AudioStreamPlaybackResampled.Instance{pointers.AsA[gdclass.AudioStreamPlaybackResampled](self[0])}
}
func (self class) AsAudioStreamPlayback() AudioStreamPlayback.Advanced {
	return AudioStreamPlayback.Advanced{pointers.AsA[gdclass.AudioStreamPlayback](self[0])}
}
func (self *Extension[T]) AsAudioStreamPlayback() AudioStreamPlayback.Instance {
	return self.Super().AsAudioStreamPlayback()
}
func (self Instance) AsAudioStreamPlayback() AudioStreamPlayback.Instance {
	return AudioStreamPlayback.Instance{pointers.AsA[gdclass.AudioStreamPlayback](self[0])}
}
func (self class) AsRefCounted() [1]gd.RefCounted {
	return [1]gd.RefCounted{gd.RefCounted(pointers.AsA[gd.Object](self[0]))}
}
func (self *Extension[T]) AsRefCounted() [1]gd.RefCounted { return self.Super().AsRefCounted() }
func (self Instance) AsRefCounted() [1]gd.RefCounted {
	return [1]gd.RefCounted{gd.RefCounted(pointers.AsA[gd.Object](self[0]))}
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AudioStreamPlaybackResampled.Advanced(self.AsAudioStreamPlaybackResampled()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AudioStreamPlaybackResampled.Instance(self.AsAudioStreamPlaybackResampled()), name)
	}
}
func init() {
	gdclass.Register("AudioStreamGeneratorPlayback", func(ptr gd.Object) any { return Instance{pointers.AsA[gdclass.AudioStreamGeneratorPlayback](ptr)} })
}
