package gdclass

/*type AudioFrame = gd.AudioFrame

type PhysicsServer2DExtensionMotionResult = gd.PhysicsServer2DExtensionMotionResult
type PhysicsServer2DExtensionRayResult = gd.PhysicsServer2DExtensionRayResult
type PhysicsServer2DExtensionShapeRestInfo = gd.PhysicsServer2DExtensionShapeRestInfo
type PhysicsServer2DExtensionShapeResult = gd.PhysicsServer2DExtensionShapeResult
type PhysicsServer3DExtensionRayResult = gd.PhysicsServer3DExtensionRayResult
type PhysicsServer3DExtensionShapeResult = gd.PhysicsServer3DExtensionShapeResult
type PhysicsServer3DExtensionShapeRestInfo = gd.PhysicsServer3DExtensionShapeRestInfo
type PhysicsServer3DExtensionMotionCollision = gd.PhysicsServer3DExtensionMotionCollision
type PhysicsServer3DExtensionMotionResult = gd.PhysicsServer3DExtensionMotionResult
type ScriptLanguageExtensionProfilingInfo = gd.ScriptLanguageExtensionProfilingInfo
type Glyph = gd.Glyph
type CaretInfo = gd.CaretInfo*/
