package PhysicsDirectSpaceState3DExtension

import gd "graphics.gd/internal"

type PhysicsServer3DExtensionRayResult = gd.PhysicsServer3DExtensionRayResult
type PhysicsServer3DExtensionShapeResult = gd.PhysicsServer3DExtensionShapeResult
type PhysicsServer3DExtensionShapeRestInfo = gd.PhysicsServer3DExtensionShapeRestInfo
type PhysicsServer3DExtensionMotionResult = gd.PhysicsServer3DExtensionMotionResult
