extends Converter

func _init():
    if HelloWorld() != "Hello, World!":         fail("HelloWorld()")
    if Echo("1234") != "1234":                  fail("Echo()")
    if Int() != 22:                             fail("Int()")
    if Float64() != 2.2:                        fail("Float64()")
    if Float32() != 2.0:                        fail("Float32()")
    if Bool() != true:                          fail("Bool()")
    if Int8() != 8:                             fail("Int8()")
    if Int16() != 16:                           fail("Int16()")
    if Int32() != 32:                           fail("Int32()")
    if Int64() != 64:                           fail("Int64()")
    if Uint() != 22:                            fail("UInt()")
    if Uint8() != 8:                            fail("UInt8()")
    if Uint16() != 16:                          fail("UInt16()")
    if Uint32() != 32:                          fail("UInt32()")
    if Uint64().get_id() != 64:                 fail("UInt64()")
    if self.RID() != rid_from_int64(22):        fail("RID()")
    if self.Complex64() != Vector2(2.0, 2.0):   fail("Complex32()")
    if self.Complex128() != Vector2(2.2, 2.2):  fail("Complex64()")

    if self.Float() != 2.2:                       fail("Float()")
    if self.String() != "testing":                fail("String()")
    if self.Vector2() != Vector2(1.0, 2.0):       fail("Vector2()")
    if self.Vector2i() != Vector2i(1, 2):         fail("Vector2i()")
    if self.Rect2() != Rect2(1.0, 2.0, 3.0, 4.0): fail("Rect2()")
    if self.Rect2i() != Rect2i(1, 2, 3, 4):       fail("Rect2i()")
    if self.Vector3() != Vector3(1.0, 2.0, 3.0):  fail("Vector3()")
    if self.Vector3i() != Vector3i(1, 2, 3):      fail("Vector3i()")
    if GetTransform2D() != Transform2D.IDENTITY:  fail("Transform2D()")
    if self.Vector4() != Vector4(1.0, 2.0, 3.0, 4.0):  fail("Vector4()")
    if self.Vector4i() != Vector4i(1, 2, 3, 4):        fail("Vector4i()")
    if self.Plane() != Plane(Vector3(1.0, 2.0, 3.0), 4.0): fail("Plane()")
    if self.GetQuaternion() != Quaternion.IDENTITY:         fail("GetQuaternion()")
    if self.AABB() != AABB(Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0)): fail("AABB()")
    if self.GetBasis() != Basis.IDENTITY:                       fail("Basis()")
    if self.GetTransform3D() != Transform3D.IDENTITY:          fail("Transform3D()")
    if self.GetProjection() != Projection.IDENTITY:        fail("Projection()")
    if self.Color() != Color(1.0, 0.0, 0.0, 1.0):      fail("Color()")
    if self.StringName() != "testing":                     fail("StringName()")
    if self.NodePath() != NodePath("/"):             fail("NodePath()")

    var obj = self.Object()
    if obj.get_class() != "Object":         fail("Object()")
    obj.free()

    var callable = self.Callable()
    if callable.call() != "Hello, World!":                    fail("Callable()")

    var sig = self.Signal()
    if sig.get_name() != "property_list_changed":       fail("Signal()")

    var dict = self.Dictionary()
    if dict.size() != 1:                                fail("Dictionary()")
    if dict.has("hello") == false:                        fail("Dictionary()")
    if dict.get("hello") != "world":                      fail("Dictionary()")

    var arr = self.Array()
    if arr.size() != 3:                                  fail("Array()")
    if arr[0] != 1:                                  fail("Array()")
    if arr[1] != 2:                                  fail("Array()")
    if arr[2] != 3:                                  fail("Array()")

    if self.PackedByteArray() != PackedByteArray([1, 2, 3]): fail("PackedByteArray()")
    if self.PackedInt32Array() != PackedInt32Array([1, 2, 3]): fail("PackedInt32Array()")
    if self.PackedInt64Array() != PackedInt64Array([1, 2, 3]): fail("PackedInt64Array()")
    if self.PackedFloat32Array() != PackedFloat32Array([1.0, 2.0, 3.0]): fail("PackedFloat32Array()")
    if self.PackedFloat64Array() != PackedFloat64Array([1.0, 2.0, 3.0]): fail("PackedFloat64Array()")
    if self.PackedStringArray() != PackedStringArray(["hello", "world"]): fail("PackedStringArray()")
    if self.PackedVector2Array() != PackedVector2Array([Vector2(1.0, 2.0), Vector2(3.0, 4.0)]): fail("PackedVector2Array()")
    if self.PackedVector3Array() != PackedVector3Array([Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0)]): fail("PackedVector3Array()")
    if self.PackedColorArray() != PackedColorArray([Color(1.0, 2.0, 3.0, 4.0), Color(5.0, 6.0, 7.0, 8.0)]): fail("PackedColorArray()")
    if self.PackedVector4Array() != PackedVector4Array([Vector4(1.0, 2.0, 3.0, 4.0), Vector4(5.0, 6.0, 7.0, 8.0)]): fail("PackedVector4Array()")

    Done()

func fail(name: String):
    push_error(name + " failed")
    Fail()
