extends Converter

func _init():
    if HelloWorld() != "Hello, World!":         fail("HelloWorld()")
    if Echo("1234") != "1234":                  fail("Echo()")
    if Int() != 22:                             fail("Int()")
    if !ValidInt(22):                           fail("ValidInt()")
    if Float64() != 2.2:                        fail("Float64()")
    if !ValidFloat64(2.2):                      fail("ValidFloat64()")
    if Float32() != 2.0:                        fail("Float32()")
    if !ValidFloat32(2.0):                      fail("ValidFloat32()")
    if Bool() != true:                          fail("Bool()")
    if !ValidBool(true):                        fail("ValidBool()")
    if Int8() != 8:                             fail("Int8()")
    if !ValidInt8(8):                           fail("ValidInt8()")
    if Int16() != 16:                           fail("Int16()")
    if !ValidInt16(16):                         fail("ValidInt16()")
    if Int32() != 32:                           fail("Int32()")
    if !ValidInt32(32):                         fail("ValidInt32()")
    if Int64() != 64:                           fail("Int64()")
    if !ValidInt64(64):                         fail("ValidInt64()")
    if Uint() != 22:                            fail("UInt()")
    if !ValidUint(22):                          fail("ValidUInt()")
    if Uint8() != 8:                            fail("UInt8()")
    if !ValidUint8(8):                          fail("ValidUInt8()")
    if Uint16() != 16:                          fail("UInt16()")
    if !ValidUint16(16):                        fail("ValidUInt16()")
    if Uint32() != 32:                          fail("UInt32()")
    if !ValidUint32(32):                        fail("ValidUInt32()")
    if Uint64().get_id() != 64:                 fail("UInt64()")
    if !ValidUint64(rid_from_int64(64)):        fail("ValidUInt64()")
    if self.RID() != rid_from_int64(22):        fail("RID()")
    if !ValidRID(rid_from_int64(22)):           fail("ValidRID()")
    if self.Complex64() != Vector2(2.0, 2.0):   fail("Complex32()")
    if !ValidComplex64(Vector2(2.0, 2.0)):      fail("ValidComplex32()")
    if self.Complex128() != Vector2(2.0, 2.0):  fail("Complex64()")
    if !ValidComplex128(Vector2(2.0, 2.0)):     fail("ValidComplex128()")

    if self.Float() != 2.2:                       fail("Float()")
    if !ValidFloat(2.2):                          fail("ValidFloat()")
    if self.String() != "testing":                fail("String()")
    if !ValidString("testing"):                   fail("ValidString()")
    if self.Vector2() != Vector2(1.0, 2.0):       fail("Vector2()")
    if !ValidVector2(Vector2(1.0, 2.0)):          fail("ValidVector2()")
    if self.Vector2i() != Vector2i(1, 2):         fail("Vector2i()")
    if !ValidVector2i(Vector2i(1, 2)):            fail("ValidVector2i()")
    if self.Rect2() != Rect2(1.0, 2.0, 3.0, 4.0): fail("Rect2()")
    if !ValidRect2(Rect2(1.0, 2.0, 3.0, 4.0)):   fail("ValidRect2()")
    if self.Rect2i() != Rect2i(1, 2, 3, 4):       fail("Rect2i()")
    if !ValidRect2i(Rect2i(1, 2, 3, 4)):          fail("ValidRect2i()")
    if self.Vector3() != Vector3(1.0, 2.0, 3.0):  fail("Vector3()")
    if !ValidVector3(Vector3(1.0, 2.0, 3.0)):     fail("ValidVector3()")
    if self.Vector3i() != Vector3i(1, 2, 3):      fail("Vector3i()")
    if !ValidVector3i(Vector3i(1, 2, 3)):         fail("ValidVector3i()")
    if GetTransform2D() != Transform2D.IDENTITY:  fail("Transform2D()")
    if !ValidTransform2D(Transform2D.IDENTITY):   fail("ValidTransform2D()")
    if self.Vector4() != Vector4(1.0, 2.0, 3.0, 4.0):  fail("Vector4()")
    if !ValidVector4(Vector4(1.0, 2.0, 3.0, 4.0)):     fail("ValidVector4()")
    if self.Vector4i() != Vector4i(1, 2, 3, 4):        fail("Vector4i()")
    if !ValidVector4i(Vector4i(1, 2, 3, 4)):           fail("ValidVector4i()")
    if self.Plane() != Plane(Vector3(1.0, 2.0, 3.0), 4.0): fail("Plane()")
    if !ValidPlane(Plane(Vector3(1.0, 2.0, 3.0), 4.0)):    fail("ValidPlane()")
    if self.GetQuaternion() != Quaternion.IDENTITY:         fail("GetQuaternion()")
    if !ValidQuaternion(Quaternion.IDENTITY):               fail("ValidQuaternion()")
    if self.AABB() != AABB(Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0)): fail("AABB()")
    if !ValidAABB(AABB(Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0))): fail("ValidAABB()")
    if self.GetBasis() != Basis.IDENTITY:                       fail("Basis()")
    if !ValidBasis(Basis.IDENTITY):                             fail("ValidBasis()")
    if self.GetTransform3D() != Transform3D.IDENTITY:          fail("Transform3D()")
    if !ValidTransform3D(Transform3D.IDENTITY):                fail("ValidTransform3D()")
    if self.GetProjection() != Projection.IDENTITY:        fail("Projection()")
    if !ValidProjection(Projection.IDENTITY):              fail("ValidProjection()")
    if self.Color() != Color(1.0, 0.0, 0.0, 1.0):      fail("Color()")
    if !ValidColor(Color(1.0, 0.0, 0.0, 1.0)):         fail("ValidColor()")
    if self.StringName() != "testing":                     fail("StringName()")
    if !ValidStringName("testing"):                        fail("ValidStringName()")
    if self.NodePath() != NodePath("/"):             fail("NodePath()")
    if !ValidNodePath(NodePath("/")):                fail("ValidNodePath()")

    var obj = self.Object()
    if obj.get_class() != "Object":         fail("Object()")
    if !ValidObject(obj):                   fail("ValidObject()")
    obj.free()

    var callable = self.Callable()
    if callable.call() != "Hello, World!":                    fail("Callable()")
    if !ValidCallable(callable):                  fail("ValidCallable()")

    var sig = self.Signal()
    if sig.get_name() != "property_list_changed":       fail("Signal()")
    if !ValidSignal(sig):                              fail("ValidSignal()")

    var dict = self.Dictionary()
    if dict.size() != 1:                                fail("Dictionary()")
    if dict.has("hello") == false:                        fail("Dictionary()")
    if dict.get("hello") != "world":                      fail("Dictionary()")
    if !ValidDictionary(dict):                          fail("ValidDictionary()")

    var arr = self.Array()
    if arr.size() != 3:                                  fail("Array()")
    if arr[0] != 1:                                  fail("Array()")
    if arr[1] != 2:                                  fail("Array()")
    if arr[2] != 3:                                  fail("Array()")
    if !ValidArray(arr):                                fail("ValidArray()")

    if self.PackedByteArray() != PackedByteArray([1, 2, 3]): fail("PackedByteArray()")
    if !ValidPackedByteArray(PackedByteArray([1, 2, 3])): fail("ValidPackedByteArray()")
    if self.PackedInt32Array() != PackedInt32Array([1, 2, 3]): fail("PackedInt32Array()")
    if !ValidPackedInt32Array(PackedInt32Array([1, 2, 3])): fail("ValidPackedInt32Array()")
    if self.PackedInt64Array() != PackedInt64Array([1, 2, 3]): fail("PackedInt64Array()")
    if !ValidPackedInt64Array(PackedInt64Array([1, 2, 3])): fail("ValidPackedInt64Array()")
    if self.PackedFloat32Array() != PackedFloat32Array([1.0, 2.0, 3.0]): fail("PackedFloat32Array()")
    if !ValidPackedFloat32Array(PackedFloat32Array([1.0, 2.0, 3.0])): fail("ValidPackedFloat32Array()")
    if self.PackedFloat64Array() != PackedFloat64Array([1.0, 2.0, 3.0]): fail("PackedFloat64Array()")
    if !ValidPackedFloat64Array(PackedFloat64Array([1.0, 2.0, 3.0])): fail("ValidPackedFloat64Array()")
    if self.PackedStringArray() != PackedStringArray(["hello", "world"]): fail("PackedStringArray()")
    if !ValidPackedStringArray(PackedStringArray(["hello", "world"])): fail("ValidPackedStringArray()")
    if self.PackedVector2Array() != PackedVector2Array([Vector2(1.0, 2.0), Vector2(3.0, 4.0)]): fail("PackedVector2Array()")
    if !ValidPackedVector2Array(PackedVector2Array([Vector2(1.0, 2.0), Vector2(3.0, 4.0)])): fail("ValidPackedVector2Array()")
    if self.PackedVector3Array() != PackedVector3Array([Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0)]): fail("PackedVector3Array()")
    if !ValidPackedVector3Array(PackedVector3Array([Vector3(1.0, 2.0, 3.0), Vector3(4.0, 5.0, 6.0)])): fail("ValidPackedVector3Array()")
    if self.PackedColorArray() != PackedColorArray([Color(1.0, 2.0, 3.0, 4.0), Color(5.0, 6.0, 7.0, 8.0)]): fail("PackedColorArray()")
    if !ValidPackedColorArray(PackedColorArray([Color(1.0, 2.0, 3.0, 4.0), Color(5.0, 6.0, 7.0, 8.0)])): fail("ValidPackedColorArray()")
    if self.PackedVector4Array() != PackedVector4Array([Vector4(1.0, 2.0, 3.0, 4.0), Vector4(5.0, 6.0, 7.0, 8.0)]): fail("PackedVector4Array()")
    if !ValidPackedVector4Array(PackedVector4Array([Vector4(1.0, 2.0, 3.0, 4.0), Vector4(5.0, 6.0, 7.0, 8.0)])): fail("ValidPackedVector4Array()")

    Done()

func fail(name: String):
    push_error(name + " failed")
    Fail()
