package gdjson

var Callables = map[string][]string{
	"Control.set_drag_forwarding.drag_func":                              {"Variant", "Vector2 at_position"},
	"Control.set_drag_forwarding.can_drop_func":                          {"bool", "Vector2 at_position", "Variant data"},
	"Control.set_drag_forwarding.drop_func":                              {"void", "Vector2 at_position", "Variant data"},
	"DisplayServer.help_set_search_callbacks.search_callback":            {"Dictionary", "String search_string", "int result_limit"},
	"DisplayServer.help_set_search_callbacks.action_callback":            {"void", "String key"},
	"DisplayServer.global_menu_set_popup_callbacks.open_callback":        {"void"},
	"DisplayServer.global_menu_set_popup_callbacks.close_callback":       {"void"},
	"DisplayServer.global_menu_add_item.callback":                        {"void", "Variant tag"},
	"DisplayServer.global_menu_add_item.key_callback":                    {"void", "Variant tag"},
	"DisplayServer.global_menu_add_check_item.callback":                  {"void", "Variant tag"},
	"DisplayServer.global_menu_add_check_item.key_callback":              {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_item.callback":                   {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_item.key_callback":               {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_check_item.callback":             {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_check_item.key_callback":         {"void", "Variant tag"},
	"DisplayServer.global_menu_add_radio_check_item.callback":            {"void", "Variant tag"},
	"DisplayServer.global_menu_add_radio_check_item.key_callback":        {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_radio_check_item.callback":       {"void", "Variant tag"},
	"DisplayServer.global_menu_add_icon_radio_check_item.key_callback":   {"void", "Variant tag"},
	"DisplayServer.global_menu_add_multistate_item.callback":             {"void", "Variant tag"},
	"DisplayServer.global_menu_add_multistate_item.key_callback":         {"void", "Variant tag"},
	"DisplayServer.global_menu_get_item_callback.":                       {"void", "Variant tag"},
	"DisplayServer.global_menu_get_item_key_callback.":                   {"void", "Variant tag"},
	"DisplayServer.global_menu_set_item_callback.callback":               {"void", "Variant tag"},
	"DisplayServer.global_menu_set_item_hover_callbacks.callback":        {"void", "Variant tag"},
	"DisplayServer.global_menu_set_item_key_callback.key_callback":       {"void", "Variant tag"},
	"DisplayServer.tts_set_utterance_callback.callable":                  {"void", "int", "int"},
	"DisplayServer.set_system_theme_change_callback.callable":            {"void"},
	"DisplayServer.window_set_rect_changed_callback.callback":            {"void", "Rect2 rect"},
	"DisplayServer.window_set_window_event_callback.callback":            {"void", "enum::DisplayServer.WindowEvent event"},
	"DisplayServer.window_set_input_event_callback.callback":             {"void", "InputEvent event"},
	"DisplayServer.window_set_input_text_callback.callback":              {"void", "String text"},
	"DisplayServer.window_set_drop_files_callback.callback":              {"void", "Variant tag"},
	"DisplayServer.dialog_show.callback":                                 {"void", "int button"},
	"DisplayServer.dialog_input_text.callback":                           {"void", "String text"},
	"DisplayServer.file_dialog_show.callback":                            {"void", "bool status", "PackedStringArray selected_paths", "int selected_filter_index"},
	"DisplayServer.file_dialog_with_options_show.callback":               {"void", "bool status", "PackedStringArray selected_paths", "int selected_filter_index", "Dictionary selected_option"},
	"DisplayServer.create_status_indicator.callback":                     {"void", "enum::MouseButton button", "Vector2i click_position"},
	"DisplayServer.status_indicator_set_callback.callback":               {"void", "enum::MouseButton button", "Vector2i click_position"},
	"EditorCommandPalette.add_command.binded_callable":                   {"void"},
	"EditorInterface.popup_node_selector.callback":                       {"void", "NodePath selected"},
	"EditorInterface.popup_property_selector.callback":                   {"void", "NodePath selected"},
	"EditorPlugin.add_tool_menu_item.callable":                           {"void"},
	"EditorPlugin.add_undo_redo_inspector_hook_callback.callable":        {"void", "Object undo_redo", "Object modified_object", "String property", "Variant new_value"},
	"EditorPlugin.remove_undo_redo_inspector_hook_callback.callable":     {},
	"EngineDebugger.register_message_capture.callable":                   {"void", "String message", "Array data"},
	"JavaScriptBridge.create_callback.callable":                          {},
	"MultiplayerSpawner.get_spawn_function.":                             {"Node", "Variant data"},
	"MultiplayerSpawner.set_spawn_function.spawn_function":               {"Node", "Variant data"},
	"MultiplayerSynchronizer.add_visibility_filter.filter":               {"bool", "int peer_id"},
	"MultiplayerSynchronizer.remove_visibility_filter.filter":            {},
	"NativeMenu.set_popup_open_callback.callback":                        {"void"},
	"NativeMenu.get_popup_open_callback.":                                {"void"},
	"NativeMenu.set_popup_close_callback.callback":                       {"void"},
	"NativeMenu.get_popup_close_callback.":                               {"void"},
	"NativeMenu.add_item.callback":                                       {"void", "Variant tag"},
	"NativeMenu.add_item.key_callback":                                   {"void", "Variant tag"},
	"NativeMenu.add_check_item.callback":                                 {"void", "Variant tag"},
	"NativeMenu.add_check_item.key_callback":                             {"void", "Variant tag"},
	"NativeMenu.add_icon_item.callback":                                  {"void", "Variant tag"},
	"NativeMenu.add_icon_item.key_callback":                              {"void", "Variant tag"},
	"NativeMenu.add_icon_check_item.callback":                            {"void", "Variant tag"},
	"NativeMenu.add_icon_check_item.key_callback":                        {"void", "Variant tag"},
	"NativeMenu.add_radio_check_item.callback":                           {"void", "Variant tag"},
	"NativeMenu.add_radio_check_item.key_callback":                       {"void", "Variant tag"},
	"NativeMenu.add_icon_radio_check_item.callback":                      {"void", "Variant tag"},
	"NativeMenu.add_icon_radio_check_item.key_callback":                  {"void", "Variant tag"},
	"NativeMenu.add_multistate_item.callback":                            {"void", "Variant tag"},
	"NativeMenu.add_multistate_item.key_callback":                        {"void", "Variant tag"},
	"NativeMenu.get_item_callback.":                                      {"void", "Variant tag"},
	"NativeMenu.get_item_key_callback.":                                  {"void", "Variant tag"},
	"NativeMenu.set_item_callback.callback":                              {"void", "Variant tag"},
	"NativeMenu.set_item_hover_callbacks.callback":                       {"void", "Variant tag"},
	"NativeMenu.set_item_key_callback.key_callback":                      {"void", "Variant tag"},
	"NavigationMeshGenerator.parse_source_geometry_data.callback":        {"void"},
	"NavigationMeshGenerator.bake_from_source_geometry_data.callback":    {"void"},
	"NavigationServer2D.agent_set_avoidance_callback.callback":           {"void", "Vector2 velocity"},
	"NavigationServer2D.parse_source_geometry_data.callback":             {"void"},
	"NavigationServer2D.bake_from_source_geometry_data.callback":         {"void"},
	"NavigationServer2D.bake_from_source_geometry_data_async.callback":   {"void"},
	"NavigationServer2D.source_geometry_parser_set_callback.callback":    {"void", "NavigationPolygon navigation_mesh", "NavigationMeshSourceGeometryData2D source_geometry_data", "Node node"},
	"NavigationServer3D.agent_set_avoidance_callback.callback":           {"void", "Vector3 velocity"},
	"NavigationServer3D.parse_source_geometry_data.callback":             {"void"},
	"NavigationServer3D.bake_from_source_geometry_data.callback":         {"void"},
	"NavigationServer3D.bake_from_source_geometry_data_async.callback":   {"void"},
	"NavigationServer3D.source_geometry_parser_set_callback.callback":    {"void", "NavigationPolygon navigation_mesh", "NavigationMeshSourceGeometryData3D source_geometry_data", "Node node"},
	"Object.connect.callable":                                            {},
	"Object.disconnect.callable":                                         {},
	"Object.is_connected.callable":                                       {},
	"Performance.add_custom_monitor.callable":                            {},
	"PhysicsServer2D.area_set_monitor_callback.callback":                 {"void", "int status", "RID body_rid", "ObjectID instance_id", "int body_shape_idx", "int self_shape_idx"},
	"PhysicsServer2D.area_set_area_monitor_callback.callback":            {"void", "int status", "RID body_rid", "ObjectID instance_id", "int body_shape_idx", "int self_shape_idx"},
	"PhysicsServer2D.body_set_state_sync_callback.callable":              {"void", "PhysicsDirectBodyState2D state"},
	"PhysicsServer2D.body_set_force_integration_callback.callable":       {"void", "PhysicsDirectBodyState2D state", "Variant userdata"},
	"PhysicsServer2DManager.register_server.create_callback":             {"PhysicsServer2D"},
	"PhysicsServer3D.area_set_monitor_callback.callback":                 {"void", "int status", "RID body_rid", "ObjectID instance_id", "int body_shape_idx", "int self_shape_idx"},
	"PhysicsServer3D.area_set_area_monitor_callback.callback":            {"void", "int status", "RID body_rid", "ObjectID instance_id", "int body_shape_idx", "int self_shape_idx"},
	"PhysicsServer3D.body_set_state_sync_callback.callable":              {"void", "PhysicsDirectBodyState3D state"},
	"PhysicsServer3D.body_set_force_integration_callback.callable":       {"void", "PhysicsDirectBodyState3D state", "Variant userdata"},
	"PhysicsServer3DManager.register_server.create_callback":             {"PhysicsServer3D"},
	"PropertyTweener.set_custom_interpolator.interpolator_method":        {"float", "float"},
	"RenderingServer.visibility_notifier_set_callbacks.enter_callable":   {"void"},
	"RenderingServer.visibility_notifier_set_callbacks.exit_callable":    {"void"},
	"RenderingServer.compositor_effect_set_callback.callback":            {"void"},
	"RenderingServer.canvas_item_set_visibility_notifier.enter_callable": {"void"},
	"RenderingServer.canvas_item_set_visibility_notifier.exit_callable":  {"void"},
	"RenderingServer.request_frame_drawn_callback.callable":              {"void"},
	"RenderingServer.call_on_render_thread.callable":                     {"void"},
	"SceneMultiplayer.set_auth_callback.callback":                        {"void"},
	"SceneMultiplayer.get_auth_callback.":                                {"void"},
	"TextEdit.set_tooltip_request_func.callback":                         {"String", "String hovered_word"},
	"TextEdit.set_gutter_custom_draw.draw_callback":                      {"void", "int line", "int gutter", "Rect2 area"},
	"Thread.start.callable":                                              {"void"},
	"TreeItem.set_custom_draw_callback.callback":                         {"void", "TreeItem item", "Rect2 rect"},
	"TreeItem.get_custom_draw_callback.":                                 {"void", "TreeItem item", "Rect2 rect"},
	"Tween.tween_callback.callback":                                      {"void"},
	"Tween.tween_method.method":                                          {"void", "Variant value"},
	"UndoRedo.add_do_method.callable":                                    {"void"},
	"UndoRedo.add_undo_method.callable":                                  {"void"},
	"WorkerThreadPool.add_task.action":                                   {"void"},
	"WorkerThreadPool.add_group_task.action":                             {"void"},
}
