package gdjson

var Distinctions = map[string][][3]string{
	"AStar2D":                        {{"id", "int", "Point"}, {"get_id_path ", "PackedInt64Array", "[]Point"}, {"get_point_connections ", "PackedInt64Array", "[]Point"}, {"get_point_ids ", "PackedInt64Array", "[]Point"}},
	"AStar3D":                        {{"id", "int", "Point"}, {"get_id_path ", "PackedInt64Array", "[]Point"}, {"get_point_connections ", "PackedInt64Array", "[]Point"}, {"get_point_ids ", "PackedInt64Array", "[]Point"}},
	"AStarGrid2D":                    {{"id", "Vector2i", "Point"}, {"get_id_path ", "typedarray::Vector2i", "[]Point"}, {"get_point_connections ", "typedarray::Vector2i", "[]Point"}, {"get_point_ids ", "typedarray::Vector2i", "[]Point"}},
	"AudioServer":                    {{"bus_idx", "int", "Bus"}, {"effect_idx", "int", "Effect"}, {"bus index", "int", "Bus"}},
	"AudioStreamInteractive":         {{"clip", "int", "Clip"}},
	"AudioStreamPlaybackInteractive": {{"clip", "int", "AudioStreamInteractive.Clip"}, {"get_current_clip_index ", "int", "AudioStreamInteractive.Clip"}},
	"AudioStreamPlaybackPolyphonic":  {{"stream", "int", "Stream"}},
	"AudioStreamPlayer3D":            {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}, {"angle_degrees", "float", "Angle.Degrees"}, {"angle_degrees ", "float", "Angle.Degrees"}},
	"Bone2D":                         {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"CanvasItem":                     {{"rotation", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}, {"angle", "float", "Angle.Radians"}},
	"CanvasLayer":                    {{"rotation", "float", "Angle.Radians"}, {"rotation ", "float", "Angle.Radians"}},
	"Control":                        {{"rotation ", "float", "Angle.Radians"}, {"rotation_degrees ", "float", "Angle.Degrees"}},
	"CharacterBody2D":                {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}, {"rotation_degrees ", "float", "Angle.Degrees"}, {"rotation ", "float", "Angle.Radians"}},
	"CharacterBody3D":                {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"CPUParticles3D":                 {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"CSGPolygon3D":                   {{"angle ", "float", "Angle.Radians"}},
	"DisplayServer":                  {{"screen", "int", "Screen"}, {"status_indicator id", "int", "StatusIndicator"}, {"create_status_indicator ", "int", "StatusIndicator"}, {"window_id", "int", "Window"}},
	"ENetPacketPeer":                 {{"flags", "int", "Flags"}},
	"EditorSceneFormatImporter":      {{"import_ flags", "int", "Flags"}},
	"Environment":                    {{"sky_rotation ", "Vector3", "Euler.Radians"}},
	"GLTFState":                      {{"handle_binary_image ", "int", "BinaryHandler"}},
	"GLTFLight":                      {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"GridMap":                        {{"item", "int", "CellItem"}, {"get_cell_item ", "int", "CellItem"}},
	"ImporterMesh":                   {{"_angle", "float", "Angle.Degrees"}},
	"Input":                          {{"device", "int", "Device"}},
	"InputEvent":                     {{"device value", "int", "Input.Device"}},
	"KinematicCollision2D":           {{"angle ", "float", "Angle.Radians"}},
	"KinematicCollision3D":           {{"angle ", "float", "Angle.Radians"}},
	"LookAtModifier3D":               {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"Material":                       {{"render_priority ", "int", "RenderPriority"}},
	"MultiplayerPeer":                {{"set_target_peer id", "int", "TargetPeer"}},
	"Node3D":                         {{"angle", "float", "Angle.Radians"}, {"rotation_degrees ", "Vector3", "Euler.Degrees"}, {"rotation ", "Vector3", "Euler.Radians"}},
	"Node2D":                         {{"radians", "float", "Angle.Radians"}, {"rotation_degrees ", "float", "Angle.Degrees"}, {"rotation ", "float", "Angle.Radians"}, {"get_angle_to ", "float", "Angle.Radians"}},
	"OpenXRCompositionLayerCylinder": {{"angle ", "float", "Angle.Radians"}},
	"OpenXRDpadBindingModifier":      {{"angle ", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"OpenXRCompositionLayerEquirect": {{"angle ", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"Polygon2D":                      {{"rotation", "float", "Angle.Radians"}, {"rotation ", "float", "Angle.Radians"}},
	"ParticleProcessMaterial":        {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"ProceduralSkyMaterial":          {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}},
	"PhysicalBone3D":                 {{"joint_rotation ", "Vector3", "Euler.Radians"}},
	"RenderingServer":                {{"emit_flags", "int", "ParticlesEmitFlag"}},
	"ResourceUID":                    {{"id", "int", "Resource.UID"}},
	"SkeletonModification2D":         {{"angle", "float", "Angle.Radians"}, {"clamp_angle min", "float", "Angle.Radians"}, {"clamp_angle max", "float", "Angle.Radians"}, {"clamp_angle ", "float", "Angle.Radians"}},
	"SkeletonModification2DLookAt":   {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}, {"rotation", "float", "Angle.Radians"}, {"get_additional_rotation ", "float", "Angle.Radians"}},
	"SkeletonModification2DCCDIK":    {{"angle", "float", "Angle.Radians"}, {"angle ", "float", "Angle.Radians"}, {"clamp_angle max", "float", "Angle.Radians"}},
	"TextureProgressBar":             {{"angle ", "float", "Angle.Radians"}},
	"VisualShader":                   {{"node", "int", "NodeID"}, {"id ", "int", "NodeID"}},
}
