package main

// https://www.khronos.org/files/opengles3-quick-reference-card.pdf
var builtins = map[string][][]string{
	"TX radians":            {{"TX"}},
	"TX degrees":            {{"TX"}},
	"TX sin":                {{"TX"}},
	"TX cos":                {{"TX"}},
	"TX tan":                {{"TX"}},
	"TX asin":               {{"TX"}},
	"TX acos":               {{"TX"}},
	"TX atan":               {{"TX", "TX"}, {"TX"}},
	"TX sinh":               {{"TX"}},
	"TX cosh":               {{"TX"}},
	"TX tanh":               {{"TX"}},
	"TX asinh":              {{"TX"}},
	"TX acosh":              {{"TX"}},
	"TX atanh":              {{"TX"}},
	"TX pow":                {{"TX", "TX"}},
	"TX exp":                {{"TX"}},
	"TX log":                {{"TX"}},
	"TX exp2":               {{"TX"}},
	"TX log2":               {{"TX"}},
	"TX sqrt":               {{"TX"}},
	"TX inversesqrt":        {{"TX"}},
	"TX abs":                {{"TX"}},
	"TI abs":                {{"TI"}},
	"TX sign":               {{"TX"}},
	"TI sign":               {{"TI"}},
	"TX floor":              {{"TX"}},
	"TX trunc":              {{"TX"}},
	"TX round":              {{"TX"}},
	"TX roundEven":          {{"TX"}},
	"TX ceil":               {{"TX"}},
	"TX fract":              {{"TX"}},
	"TX mod":                {{"TX", "TX"}, {"TX", "float"}},
	"TX modf":               {{"TX", "out[TX]"}},
	"TX min":                {{"TX", "TX"}, {"TX", "float"}},
	"TI min":                {{"TI", "TI"}, {"TI", "int"}},
	"TU min":                {{"TU", "TU"}, {"TU", "uint"}},
	"TX max":                {{"TX", "TX"}, {"TX", "float"}},
	"TI max":                {{"TI", "TI"}, {"TI", "int"}},
	"TU max":                {{"TU", "TU"}, {"TU", "uint"}},
	"TX clamp":              {{"TX", "TX", "TX"}, {"TX", "float", "float"}},
	"TI clamp":              {{"TI", "TI", "TI"}, {"TI", "int", "int"}},
	"TU clamp":              {{"TU", "TU", "TU"}, {"TU", "uint", "uint"}},
	"TX mix":                {{"TX", "TX", "TX"}, {"TX", "float", "float"}, {"TX", "TX", "bvec"}},
	"TX step":               {{"TX", "TX"}, {"float", "TX"}},
	"TX smoothstep":         {{"TX", "TX", "TX"}, {"float", "float", "TX"}},
	"bvec isnan":            {{"TX"}},
	"bvec isinf":            {{"TX"}},
	"ivec floatBitsToInt":   {{"TX"}},
	"uvec floatBitsToUint":  {{"TX"}},
	"vec intBitsToFloat":    {{"TI"}},
	"vec uintBitsToFloat":   {{"TU"}},
	"uint packSnorm2x16":    {{"vec2"}},
	"uint packUnorm2x16":    {{"vec2"}},
	"vec2 unpackSnorm2x16":  {{"uint"}},
	"vec2 unpackUnorm2x16":  {{"uint"}},
	"uint packHalf2x16":     {{"vec2"}},
	"vec2 unpackHalf2x16":   {{"uint"}},
	"float length":          {{"TX"}},
	"float distance":        {{"TX", "TX"}},
	"float dot":             {{"TX", "TX"}},
	"vec3 cross":            {{"vec3", "vec3"}},
	"TX normalize":          {{"TX"}},
	"TX faceforward":        {{"TX", "TX", "TX"}},
	"TX reflect":            {{"TX", "TX"}},
	"TX refract":            {{"TX", "TX", "float"}},
	"matx matrixCompMult":   {{"matx", "matx"}},
	"mat2 outerProduct":     {{"vec2", "vec2"}},
	"mat3 outerProduct":     {{"vec3", "vec3"}},
	"mat4 outerProduct":     {{"vec4", "vec4"}},
	"mat2 transpose":        {{"mat2"}},
	"mat3 transpose":        {{"mat3"}},
	"mat4 transpose":        {{"mat4"}},
	"float determinant":     {{"mat2"}, {"mat3"}, {"mat4"}},
	"mat2 inverse":          {{"mat2"}},
	"mat3 inverse":          {{"mat3"}},
	"mat4 inverse":          {{"mat4"}},
	"bvec lessThan":         {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bvec lessThanEqual":    {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bvec greaterThan":      {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bvec greaterThanEqual": {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bvec equal":            {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bvec notEqual":         {{"gvec2", "gvec2"}, {"gvec3", "gvec3"}, {"gvec4", "gvec4"}},
	"bool any":              {{"B+"}},
	"bool all":              {{"B+"}},
	"B+ not":                {{"B+"}},
	"ivec2 textureSize":     {{"sampler2D", "int"}, {"samplerCube", "int"}},
	"ivec3 textureSize":     {{"sampler3D", "int"}, {"sampler2DArray", "int"}},
	"rgba texture": {
		{"sampler2D", "vec2"}, {"sampler3D", "vec3"}, {"samplerCube", "vec3"}, {"sampler2DArray", "vec3"},
		{"sampler2D", "vec2", "float"}, {"sampler3D", "vec3", "float"}, {"samplerCube", "vec3", "float"}, {"sampler2DArray", "vec3", "float"},
	},
	"rgba textureProj": {
		{"sampler2D", "vec3"}, {"sampler2D", "vec4"}, {"sampler3D", "vec4"},
		{"sampler2D", "vec3", "float"}, {"sampler3D", "vec4", "float"}, {"sampler2D", "vec4", "float"},
	},
	"rgba textureLod": {
		{"sampler2D", "vec2", "float"}, {"sampler3D", "vec3", "float"}, {"samplerCube", "vec3", "float"}, {"sampler2DArray", "vec3", "float"},
	},
	"rgba textureOffset": {
		{"sampler2D", "vec2", "ivec2"}, {"sampler3D", "vec3", "ivec3"},
		{"sampler2D", "vec2", "ivec2", "float"}, {"sampler3D", "vec3", "ivec3", "float"},
	},
	"rgba texelFetch": {
		{"sampler2D", "ivec2", "int"}, {"sampler3D", "ivec3", "int"}, {"sampler2DArray", "ivec3", "int"},
	},
	"rgba texelFetchOffset": {
		{"sampler2D", "ivec2", "int", "ivec2"},
		{"sampler3D", "ivec3", "int", "ivec3"},
		{"sampler2DArray", "ivec3", "int", "ivec2"},
	},
	"rgba textureProjOffset": {
		{"sampler2D", "vec3", "ivec2"}, {"sampler3D", "vec4", "ivec3"},
		{"sampler2D", "vec4", "ivec2"},
		{"sampler2D", "vec3", "ivec2", "float"}, {"sampler3D", "vec4", "ivec3", "float"},
		{"sampler2D", "vec4", "ivec2", "float"},
	},
	"rgba textureLodOffset": {
		{"sampler2D", "vec2", "float", "ivec2"},
		{"sampler3D", "vec3", "float", "ivec3"},
		{"sampler2DArray", "vec3", "float", "ivec2"},
	},
	"rgba textureProjLod": {
		{"sampler2D", "vec3", "float"}, {"sampler3D", "vec4", "float"},
		{"sampler2D", "vec4", "float"},
	},
	"rgba textureProjLodOffset": {
		{"sampler2D", "vec3", "float", "ivec2"}, {"sampler3D", "vec4", "float", "ivec3"},
		{"sampler2D", "vec4", "float", "ivec2"},
	},
	"rgba textureGrad": {
		{"sampler2D", "vec2", "vec2", "vec2"}, {"sampler3D", "vec3", "vec3", "vec3"},
		{"samplerCube", "vec3", "vec3", "vec3"}, {"sampler2DArray", "vec3", "vec2", "vec2"},
	},
	"rgba textureGradOffset": {
		{"sampler2D", "vec2", "vec2", "vec2", "ivec2"}, {"sampler3D", "vec3", "vec3", "vec3", "ivec3"},
		{"sampler2DArray", "vec3", "vec2", "vec2", "ivec2"},
	},
	"rgba textureProjGrad": {
		{"sampler2D", "vec3", "vec2", "vec2"}, {"sampler3D", "vec4", "vec3", "vec3"},
		{"sampler2D", "vec4", "vec2", "vec2"},
	},
	"rgba textureProjGradOffset": {
		{"sampler2D", "vec3", "vec2", "vec2", "ivec2"}, {"sampler3D", "vec4", "vec3", "vec3", "ivec3"},
		{"sampler2D", "vec4", "vec2", "vec2", "ivec2"},
	},
	"TX dFdx":   {{"TX"}},
	"TX dFdy":   {{"TX"}},
	"TX fwidth": {{"TX"}},

	// operators
	" +": {{"TX", "TX"}, {"TI", "TI"}, {"TU", "TU"}},
	" -": {{"TX"}, {"TX", "TX"}, {"TI"}, {"TI", "TI"}, {"TU", "TU"}},
	" *": {{"TX", "TX"}, {"TI", "TI"}, {"TU", "TU"}, {"matx", "matx"}},
	" /": {{"TX", "TX"}, {"TI", "TI"}, {"TU", "TU"}},
}

var expansions = map[string][]string{
	"TX":    {"float", "vec2", "vec3", "vec4"},
	"TI":    {"int", "ivec2", "ivec3", "ivec4"},
	"TU":    {"uint", "uvec2", "uvec3", "uvec4"},
	"TB":    {"bool", "bvec2", "bvec3", "bvec4"},
	"B+":    {"bvec2", "bvec3", "bvec4"},
	"gvec2": {"vec2", "ivec2", "uvec2"},
	"gvec3": {"vec3", "ivec3", "uvec3"},
	"gvec4": {"vec4", "ivec4", "uvec4"},
	"matx":  {"mat2", "mat3", "mat4"},
}
