package packages

// Audio related features, from low-level AudioServer and drivers to high-level nodes and effects.
var Audio = []string{
	"AudioBusLayout",
	"AudioEffect",
	"AudioEffectAmplify",
	"AudioEffectBandLimitFilter",
	"AudioEffectBandPassFilter",
	"AudioEffectCapture",
	"AudioEffectChorus",
	"AudioEffectCompressor",
	"AudioEffectDelay",
	"AudioEffectDistortion",
	"AudioEffectEQ",
	"AudioEffectEQ10",
	"AudioEffectEQ21",
	"AudioEffectEQ6",
	"AudioEffectFilter",
	"AudioEffectHighPassFilter",
	"AudioEffectHighShelfFilter",
	"AudioEffectInstance",
	"AudioEffectLimiter",
	"AudioEffectLowPassFilter",
	"AudioEffectLowShelfFilter",
	"AudioEffectNotchFilter",
	"AudioEffectPanner",
	"AudioEffectPhaser",
	"AudioEffectPitchShift",
	"AudioEffectRecord",
	"AudioEffectReverb",
	"AudioEffectSpectrumAnalyzer",
	"AudioEffectSpectrumAnalyzerInstance",
	"AudioEffectStereoEnhance",
	"AudioListener2D",
	"AudioListener3D",
	"AudioServer",
	"AudioStream",
	"AudioStreamGenerator",
	"AudioStreamGeneratorPlayback",
	"AudioStreamMicrophone",
	"AudioStreamMP3",
	"AudioStreamOggVorbis",
	"AudioStreamPlayback",
	"AudioStreamPlaybackOggVorbis",
	"AudioStreamPlaybackResampled",
	"AudioStreamPlayer",
	"AudioStreamPlayer2D",
	"AudioStreamPlayer3D",
	"AudioStreamRandomizer",
	"AudioStreamWAV",
}

// AudioOgg format.
var AudioOgg = []string{
	"OggPacketSequence",
	"OggPacketSequencePlayback",
}
