package packages

// Core APIs relating to the configuration and runtime of the engine + scene tree.
var Core = []string{
	"Node",
	"Node2D",
	"Node3D",
	"Node3DGizmo",
	"NodePath",
	"ProjectSettings",
	"Resource",
	"ResourceFormatLoader",
	"ResourceFormatSaver",
	"ResourceImporter",
	"ResourceLoader",
	"ResourcePreloader",
	"ResourceSaver",
	"ResourceUID",
	"RID",
	"SceneState",
	"SceneTree",
	"SceneTreeTimer",
	"World2D",
	"World3D",
}

// CoreScript is an umbrella for all the scripting languages usable with Godot.
// Encompasses some shared core components
// (Object, ClassDB, MethodBind, ScriptLanguage, etc.).
var CoreScript = []string{
	"Array",
	"bool",
	"Callable",
	"ClassDB",
	//"CSharpScript",
	"Dictionary",
	"float",
	"GDScript",
	"GDScriptEditorTranslationParserPlugin",
	"GDScriptNativeClass",
	//"GodotSharp",
	"int",
	"JavaClass",
	"JavaClassWrapper",
	"JavaScript",
	"JavaScriptObject",
	"JNISingleton",
	"NativeExtension",
	"NativeExtensionManager",
	"Nil",
	"Object",
	"RefCounted",
	"Script",
	"ScriptCreateDialog",
	"ScriptEditor",
	"ScriptEditorBase",
	"ScriptExtension",
	"ScriptLanguage",
	"ScriptLanguageExtension",
	"Signal",
	//"Variant",
	"WeakRef",
}

// CoreBinary data.
var CoreBinary = []string{
	"BitMap",
	"Marshalls",
	"PackedByteArray",
	"PackedColorArray",
	"PackedDataContainer",
	"PackedDataContainerRef",
	"PackedFloat32Array",
	"PackedFloat64Array",
	"PackedInt32Array",
	"PackedInt64Array",
	"PackedScene",
	"PackedStringArray",
	"PackedVector2Array",
	"PackedVector3Array",
	"PCKPacker",
}

// CoreEngine types.
var CoreEngine = []string{
	"Engine",
	"EngineDebugger",
	"EngineProfiler",
	"MainLoop",
	"Performance",
}

// CoreEditor related, both tools and usability.
var CoreEditor = []string{
	"EditorCommandPalette",
	"EditorDebuggerPlugin",
	"EditorExportPlatform",
	"EditorExportPlugin",
	"EditorFeatureProfile",
	"EditorFileDialog",
	"EditorFileSystem",
	"EditorFileSystemDirectory",
	"EditorFileSystemImportFormatSupportQuery",
	"EditorImportPlugin",
	"EditorInspector",
	"EditorInspectorPlugin",
	"EditorInterface",
	"EditorNode3DGizmo",
	"EditorNode3DGizmoPlugin",
	"EditorPaths",
	"EditorPlugin",
	"EditorProperty",
	"EditorResourceConversionPlugin",
	"EditorResourcePicker",
	"EditorResourcePreview",
	"EditorResourcePreviewGenerator",
	"EditorSceneFormatImporter",
	"EditorSceneFormatImporterBlend",
	"EditorSceneFormatImporterFBX",
	"EditorSceneFormatImporterGLTF",
	"EditorScenePostImport",
	"EditorScenePostImportPlugin",
	"EditorScript",
	"EditorScriptPicker",
	"EditorSelection",
	"EditorSettings",
	"EditorSpinSlider",
	"EditorSyntaxHighlighter",
	"EditorTranslationParserPlugin",
	"EditorUndoRedoManager",
	"EditorVCSInterface",
	"EncodedObjectAsID",
	"GridMap",
	"Marker2D",
	"Marker3D",
	"MissingNode",
	"MissingResource",
	"SurfaceTool",
	"UndoRedo",
}
